version: "3.6"
services:
  goservice:
    build: "./sandsack-management-backend"
    ports:
      - "8000"
    depends_on:
      - "db"
    env_file:
      - ./.env
  frontend:
    build: "./sandsack-management-frontend"
    ports:
      - "80:80"
volumes:
  database: