version: "3.6"
services:
  goservice:
    build: "./sandsack-management-backend"
    ports:
      - "8000"
    env_file:
      - ./.env
  nginx:
    build: "./nginx"
    ports:
      - "8001:8001"
    depends_on:
      - "goservice"
  frontend:
    build: "./sandsack-management-frontend"
    ports:
      - "80:80"