definitions:
  models.Logout:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /users/login:
    post:
      description: Registers new user in system. Sends verification token to email
        of the user
      tags:
      - Authentication
  /users/logout:
    post:
      consumes:
      - application/json
      description: Logout an authenticated user
      parameters:
      - description: Logout
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Logout'
      responses:
        "204":
          description: Logged out successfully
        "400":
          description: Bad request (e.g. refresh in body is not given)
        "401":
          description: Access token is missing
      summary: Logout an authenticated user
      tags:
      - Authentication
swagger: "2.0"
