version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=feuerwehr
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/1_init_schema.up.sql:/docker-entrypoint-initdb.d/1_init_schema.up.sql
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "8000:8000"